

export const FETCH_PRODUCT_REQ = 'FETCH_PRODUCT_REQ';
export const FETCH_PRODUCT_DONE ='FETCH_PRODUCT_DONE';
export const FETCH_PRODUCT_FAIL ='FETCH_PRODUCT_FAIL';

export const SELECT_PRODUCT = 'SELECT_PRODUCT'

export const  FETCH_PRODUCT_BY_ID_REQ= 'FETCH_PRODUCT_BY_ID_REQ';
export const FETCH_PRODUCT_BY_ID_DONE='FETCH_PRODUCT_BY_ID_DONE';
export const FETCH_PRODUCT_BY_ID_FAIL= 'FETCH_PRODUCT_BY_ID_FAIL';